name: Dart CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Flutter (Web)
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
          channel: 'dev'
    - run: cd player && flutter pub get
    - run: flutter config --enable-web
    - run: cd player && flutter build web --release
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: player/build/web
